# Generated by Django 4.2.7 on 2023-11-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
